development:
  cloud_name: dyrgzonq5
  api_key: 515666694398369
  api_secret: NBS2ufji-1O8fzSBARSXczq95qk
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_file_support: true
